import type { Metadata } from 'next';
import { MarketingShell, FinalCta } from '@/components/marketing/Shell';
import { CopyText } from '@/components/marketing/Interactive';
import { integrations } from '@/lib/marketing/catalog';
import { ClientInstructions } from '@/components/marketing/ClientInstructions';
import { clientGuides, mcpUrl } from '@/lib/marketing/clients';

export const metadata: Metadata = { title: 'Подключение MCP: Claude, Codex, Cursor, Cline и другие клиенты | ohmy-seo', description: 'Как подключить MCP ohmy-seo к Claude Desktop, Claude Code, Codex, BB, Cursor, Windsurf, Cline, VS Code, OpenCode и Gemini CLI. Конфигурации, проверка доступа и ограничения ChatGPT.', alternates: { canonical: '/claude-mcp' }, openGraph: { images: [{ url: "https://ohmy-seo.ru/og-image.png", width: 1200, height: 630, alt: "ohmy-seo — ваш маркетинг в диалоге с AI" }], type: "website", locale: "ru_RU", siteName: "ohmy-seo", title: 'Подключение ohmy-seo к AI-клиентам', description: 'От аккаунта до первого запроса: инструкция для Claude Code и локальных MCP-пакетов.', url: '/claude-mcp' } };
const firstPrompt = 'Покажи доступные через ohmy-seo аккаунты и источники данных. Ничего не изменяй. Если нужный источник не подключён, объясни, какое подключение требуется.';
const localConfig = JSON.stringify({ mcpServers: { 'mcp-roistat': { command: 'node', args: ['/absolute/path/to/ohmy-seo/packages/roistat/dist/index.js'], env: { ROISTAT_API_KEY: 'YOUR_ROISTAT_API_KEY', ROISTAT_PROJECT_ID: 'YOUR_PROJECT_ID' } } } }, null, 2);
export default async function ClaudeMcpPage({ searchParams }: { searchParams: Promise<{ client?: string | string[] }> }) {
  const { client } = await searchParams;
  const activeId = clientGuides.find(item => item.id === client)?.id ?? clientGuides[0].id;
  return <MarketingShell><main id="main-content"><section className="mk-container detail-hero"><nav className="breadcrumbs" aria-label="Хлебные крошки"><a href="/">Главная</a><span>/</span><span>Подключение MCP</span></nav><span className="eyebrow">ИНСТРУКЦИЯ · AI-КЛИЕНТЫ</span><h1>Подключите ohmy-seo<br />к своему AI-клиенту</h1><p className="detail-lead">Выберите приложение и скопируйте его настройки. Один ключ ohmy-seo открывает доступ к вашим подключённым аккаунтам; права и доступные инструменты зависят от сервиса.</p></section>
    <section className="mk-container connection-start" id="cloud"><h2>Сначала — аккаунты и API-ключ</h2><ol><li><strong>Войдите в кабинет</strong><p>Используйте <a href="/connect">Яндекс для входа</a>, затем отдельно добавьте рабочие аккаунты Яндекса и Google.</p></li><li><strong>Создайте ключ ohmy-seo</strong><p>Выпустите персональный API-ключ в кабинете. Ключи Яндекса и Google в конфигурацию MCP не подставляются.</p></li><li><strong>Выберите приложение ниже</strong><p>Добавьте сервер и ключ в настройки клиента, затем откройте новую сессию.</p></li></ol><p className="small">Все шаблоны содержат заглушку YOUR_API_KEY. Замените её своим ключом только в личной конфигурации — не в сообщении AI и не в публичном репозитории. Если файл уже содержит настройки, добавьте запись ohmy-seo, сохранив остальные.</p></section>
    <section className="mk-container client-section" id="clients"><h2>Настройка приложения</h2><p>Прямое подключение, локальный мост или ограничение совместимости — способ указан в каждой вкладке.</p><ClientInstructions activeId={activeId} /><p className="small">Форматы сверены с документацией разработчиков 14 сентября 2026. Доступность MCP может зависеть от версии клиента и правил вашей организации.</p></section>
    <div className="mk-container guide-layout"><article className="guide-content"><section id="verify"><h2>Первый запрос: проверить доступы</h2><blockquote>{firstPrompt}</blockquote><CopyText text={firstPrompt} /><p>Выберите из ответа аккаунт, сайт или счётчик, укажите период и задачу. Готовые запросы есть в <a href="/prompts">библиотеке вопросов</a>.</p><p>Для изменения настроек сначала попросите показать план, объект и новые значения. Облачный сервер требует подтверждения в вызове инструмента записи; проверяйте запрос на действие в своём AI-клиенте.</p><details><summary>Общие параметры подключения</summary><dl className="connection-facts"><dt>Адрес</dt><dd><code>{mcpUrl}</code></dd><dt>Транспорт</dt><dd>Streamable HTTP</dd><dt>Заголовок авторизации</dt><dd><code>Authorization: Bearer YOUR_API_KEY</code></dd></dl></details></section>
    <section id="local"><h2>Локальная установка: Google Ads, Roistat и другие пакеты</h2><p>Выберите нужный пакет в репозитории, установите зависимости и соберите проект. Требуются Node.js 22 или новее и pnpm. Облачный адрес предоставляет сервисы Яндекса, Search Console, GA4 и GTM в рамках ваших прав; Google Ads и Roistat устанавливаются отдельно.</p><pre><code>{'git clone https://github.com/VKirill/ohmy-seo.git\ncd ohmy-seo\npnpm install\npnpm -r build'}</code></pre><p>Настройте переменные из <code>.env.example</code> выбранного пакета согласно его README. Для Google Ads нужны OAuth и доступ к рекламному API; Roistat использует собственный API-ключ. Подключение Google в облачном кабинете не настраивает локальный Google Ads.</p><h3>Пример stdio-конфигурации для Roistat</h3><p>В конфигурации MCP-клиента замените абсолютный путь, API-ключ и ID проекта. Храните файл с секретами вне публичного репозитория.</p><pre><code>{localConfig}</code></pre><CopyText text={localConfig} label="Скопировать шаблон конфигурации" /><h3>Документация каждого пакета</h3><div className="guide-package-links">{Array.from(new Set(integrations.map(i=>i.package))).map(p=><a key={p} href={`https://github.com/VKirill/ohmy-seo/tree/main/packages/${p}`}>{p} ↗</a>)}</div><p>Локальная синхронизация токенов с облачным кабинетом — отдельный режим, зависящий от брокера. Самостоятельная установка пакетов требует собственных настроек доступа.</p></section>
    <section id="troubleshooting"><h2>Если подключение не заработало</h2><details><summary>Сервер отсутствует в списке инструментов</summary><p>Проверьте конфигурацию именно для вашего приложения, транспорт Streamable HTTP и заголовок авторизации. Для переменных окружения убедитесь, что их видит процесс клиента; после настройки откройте новую сессию. В Claude Code используйте <code>claude mcp list</code> и <code>/mcp</code>. Для stdio проверьте абсолютный путь и наличие собранного файла.</p></details><details><summary>Ошибка авторизации</summary><p>При 401 проверьте, что используется API-ключ ohmy-seo без лишних пробелов, а не токен Яндекса или Google. В заголовке Authorization перед ключом должно стоять Bearer и один пробел. Если клиент предлагает OAuth-вход, выберите настройку по API-ключу из соответствующей вкладки. Если ключ отозван, создайте новый в кабинете.</p></details><details><summary>Аккаунт есть, но нужных данных нет</summary><p>Проверьте права на сайт, счётчик или рекламный аккаунт. Наличие Google-подключения не добавляет Google Ads. Для Директа проверьте статус доступа приложения.</p></details><details><summary>Отчёт отличается от интерфейса сервиса</summary><p>Сверьте период, часовой пояс, фильтры, цель и модель атрибуции. Учитывайте задержки API и ограничения выборки. Попросите AI показать параметры запроса.</p></details></section></article><aside className="guide-toc"><strong>В этой инструкции</strong><a href="#cloud">Облачное подключение</a><a href="#clients">Выбор приложения</a><a href="#verify">Первый запрос</a><a href="#local">Локальные пакеты</a><a href="#troubleshooting">Решение ошибок</a><a href="/#integrations">Выбрать интеграцию ↗</a></aside></div><FinalCta /></main></MarketingShell>;
}
