import type { Metadata } from 'next';
import { MarketingShell, FinalCta } from '@/components/marketing/Shell';
import { CopyText } from '@/components/marketing/Interactive';
import { claudeCommand, integrations } from '@/lib/marketing/catalog';

export const metadata: Metadata = { title: 'Как подключить Claude к MCP: Яндекс Директ, Google и SEO | ohmy-seo', description: 'Инструкция подключения ohmy-seo к Claude Code через HTTP MCP: аккаунты, API-ключ, команда подключения, первый запрос и локальная установка пакетов.', alternates: { canonical: '/claude-mcp' }, openGraph: { images: [{ url: "https://ohmy-seo.ru/og-image.png", width: 1200, height: 630, alt: "ohmy-seo — ваш маркетинг в диалоге с AI" }], type: "website", locale: "ru_RU", siteName: "ohmy-seo", title: 'Как подключить Claude к MCP ohmy-seo', description: 'От аккаунта до первого запроса: инструкция для Claude Code и локальных MCP-пакетов.', url: '/claude-mcp' } };
const firstPrompt = 'Покажи доступные через ohmy-seo аккаунты и источники данных. Ничего не изменяй. Если нужный источник не подключён, объясни, какое подключение требуется.';
const localConfig = JSON.stringify({ mcpServers: { 'mcp-roistat': { command: 'node', args: ['/absolute/path/to/ohmy-seo/packages/roistat/dist/index.js'], env: { ROISTAT_API_KEY: 'YOUR_ROISTAT_API_KEY', ROISTAT_PROJECT_ID: 'YOUR_PROJECT_ID' } } } }, null, 2);
export default function ClaudeMcpPage() {
  return <MarketingShell><main id="main-content"><section className="mk-container detail-hero"><nav className="breadcrumbs" aria-label="Хлебные крошки"><a href="/">Главная</a><span>/</span><span>Подключение Claude MCP</span></nav><span className="eyebrow">ИНСТРУКЦИЯ · CLAUDE CODE</span><h1>Как подключить Claude<br />к вашим маркетинговым данным через MCP</h1><p className="detail-lead">Если вы ищете «Клод MCP Яндекс Директ» или «Claude MCP Google реклама», начните с выбора интеграции. Облачный ohmy-seo и отдельные пакеты подключаются по-разному.</p></section>
    <div className="mk-container guide-layout"><article className="guide-content"><section id="cloud"><h2>Облачный MCP: подключение к Claude Code</h2><p>В облаке доступны сервисы Яндекса, Search Console, GA4 и GTM в пределах прав и доступности аккаунта. Google Ads и Roistat настраиваются как отдельные пакеты.</p><h3>1. Подключите аккаунт</h3><p>Откройте <a href="/connect">страницу входа</a> и войдите через Яндекс. Внутри кабинета отдельно подключите рабочие аккаунты Яндекса или Google. Проверьте, что выбранный сервис доступен. Директ может требовать одобрения доступа API; предупреждение OAuth само по себе не подтверждает успешное подключение.</p><h3>2. Создайте персональный ключ</h3><p>В кабинете создайте API-ключ и сохраните его в надёжном месте. Используйте ключ в конфигурации клиента, не вставляйте его в обычное сообщение AI.</p><h3>3. Добавьте сервер в Claude Code</h3><p>При установленном Claude Code выполните команду в терминале, заменив <code>YOUR_API_KEY</code> своим ключом. Команда с ключом может сохраниться в истории терминала — учитывайте правила хранения секретов на своём устройстве.</p><pre><code>{claudeCommand}</code></pre><CopyText text={claudeCommand} label="Скопировать шаблон команды" /><p>Проверьте сервер через <code>claude mcp list</code>. В сессии Claude Code откройте <code>/mcp</code> и проверьте состояние подключения. При необходимости начните новую сессию.</p><p className="small">Синтаксис HTTP-подключения: <a href="https://code.claude.com/docs/en/mcp">официальная документация Claude Code</a>. Эта команда предназначена для Claude Code; интерфейсы других клиентов отличаются.</p><h3>4. Проверьте доступы первым запросом</h3><blockquote>{firstPrompt}</blockquote><CopyText text={firstPrompt} /><p>После получения списка выберите аккаунт, период и нужный отчёт. Начните с одного источника; затем добавляйте другие.</p></section>
    <section id="clients"><h2>Claude Desktop и другие AI-клиенты</h2><p>Для облачного подключения клиент должен поддерживать Streamable HTTP MCP и передачу заголовка Authorization с Bearer-ключом. Поддержка транспорта сама по себе не означает, что клиент умеет настроить такой способ авторизации.</p><dl className="connection-facts"><dt>Адрес сервера</dt><dd><code>https://mcp.ohmy-seo.ru/mcp</code></dd><dt>Заголовок</dt><dd><code>Authorization: Bearer YOUR_API_KEY</code></dd><dt>Локальные пакеты</dt><dd>Подключаются через stdio, если клиент поддерживает запуск MCP-процесса.</dd></dl><p>Для Claude Desktop и Cursor используйте актуальную инструкцию вашего клиента. Не переносите команду Claude Code в JSON-конфигурацию: это разные способы настройки.</p></section>
    <section id="local"><h2>Локальная установка: Google Ads, Roistat и другие пакеты</h2><p>Выберите нужный пакет в репозитории, установите зависимости и соберите проект. Требуются Node.js 22 или новее и pnpm.</p><pre><code>{'git clone https://github.com/VKirill/ohmy-seo.git\ncd ohmy-seo\npnpm install\npnpm -r build'}</code></pre><p>Настройте переменные из <code>.env.example</code> выбранного пакета согласно его README. Для Google Ads нужны OAuth и доступ к рекламному API; Roistat использует собственный API-ключ. Подключение Google в облачном кабинете не настраивает локальный Google Ads.</p><h3>Пример stdio-конфигурации для Roistat</h3><p>В конфигурации MCP-клиента замените абсолютный путь, API-ключ и ID проекта. Храните файл с секретами вне публичного репозитория.</p><pre><code>{localConfig}</code></pre><CopyText text={localConfig} label="Скопировать шаблон конфигурации" /><h3>Документация каждого пакета</h3><div className="guide-package-links">{Array.from(new Set(integrations.map(i=>i.package))).map(p=><a key={p} href={`https://github.com/VKirill/ohmy-seo/tree/main/packages/${p}`}>{p} ↗</a>)}</div><p>Локальная синхронизация токенов с облачным кабинетом — отдельный режим, зависящий от брокера. Самостоятельная установка пакетов требует собственных настроек доступа.</p></section>
    <section id="troubleshooting"><h2>Если подключение не заработало</h2><details><summary>Сервер отсутствует в списке инструментов</summary><p>Проверьте конфигурацию, поддержку транспорта и заголовка авторизации. В Claude Code используйте <code>claude mcp list</code> и <code>/mcp</code>. Для stdio проверьте абсолютный путь и наличие собранного файла.</p></details><details><summary>Ошибка авторизации</summary><p>Проверьте, что используется API-ключ ohmy-seo без лишних пробелов, а не токен Яндекса или Google. Если ключ отозван, создайте новый в кабинете.</p></details><details><summary>Аккаунт есть, но нужных данных нет</summary><p>Проверьте права на сайт, счётчик или рекламный аккаунт. Наличие Google-подключения не добавляет Google Ads. Для Директа проверьте статус доступа приложения.</p></details><details><summary>Отчёт отличается от интерфейса сервиса</summary><p>Сверьте период, часовой пояс, фильтры, цель и модель атрибуции. Учитывайте задержки API и ограничения выборки. Попросите AI показать параметры запроса.</p></details></section></article><aside className="guide-toc"><strong>В этой инструкции</strong><a href="#cloud">Облачное подключение</a><a href="#clients">Другие AI-клиенты</a><a href="#local">Локальные пакеты</a><a href="#troubleshooting">Решение ошибок</a><a href="/#integrations">Выбрать интеграцию ↗</a></aside></div><FinalCta /></main></MarketingShell>;
}
