import type { Metadata } from 'next';
import { ServiceLogo } from '@/components/marketing/ServiceLogo';
import { MarketingShell, FinalCta } from '@/components/marketing/Shell';
import { ScenarioDemo, CopyText } from '@/components/marketing/Interactive';
import { integrations, faqs } from '@/lib/marketing/catalog';

export const metadata: Metadata = {
  title: 'ohmy-seo — бесплатный MCP для маркетологов: Claude, Директ и Google Ads',
  description: 'Бесплатный инструмент для маркетологов: подключите Яндекс Директ, Google Ads, SEO и аналитику к Claude через MCP. Сценарии работы и инструкции.',
  alternates: { canonical: '/' },
  openGraph: { images: [{ url: "https://ohmy-seo.ru/og-image.png", width: 1200, height: 630, alt: "ohmy-seo — ваш маркетинг в диалоге с AI" }], type: "website", locale: "ru_RU", siteName: "ohmy-seo", title: 'Бесплатный MCP-инструмент для маркетологов', description: 'ohmy-seo создан специально для маркетологов: реклама, SEO и аналитика в диалоге с AI. Бесплатный доступ к инструменту.', url: '/' },
};

export default function Home() {
  return <MarketingShell><main id="main-content">
    <section className="mk-hero mk-container"><div className="hero-copy"><span className="eyebrow"><span className="live-dot" /> БЕСПЛАТНЫЙ MCP ДЛЯ МАРКЕТОЛОГОВ</span><h1>Ваш маркетинг.<br />Ваши данные.<br /><em>В диалоге с AI.</em></h1><p className="hero-lead">ohmy-seo — бесплатный инструмент, созданный специально для маркетологов. Подключите сервисы Яндекса и Google к Claude или другому AI-ассистенту. Разбирайте рекламу, находите просадки в SEO и собирайте отчёты без ручного переноса каждой выгрузки.</p><div className="mk-actions"><a className="mk-button" href="/connect">Начать бесплатно <span aria-hidden="true">↗</span></a><a className="mk-button secondary" href="#demo">Посмотреть пример ↓</a></div><p className="hero-note"><a className="text-link" href="https://github.com/VKirill/ohmy-seo" target="_blank" rel="noopener noreferrer">Открытый код на GitHub ↗</a><br />Лицензия MIT · Облачный MCP и локальные пакеты.<br />Доступные функции зависят от подключения и прав.</p></div><div id="demo"><ScenarioDemo /></div></section>
    <section className="source-strip" aria-label="Поддерживаемые сервисы"><div className="mk-container"><span>РАБОТАЙТЕ С ДАННЫМИ</span><div>{['yandex-direct', 'google-ads', 'yandex-metrica', 'google-search-console', 'google-analytics', 'roistat'].map(slug => { const service = integrations.find(i => i.slug === slug)!; return <span className="strip-service" key={slug} aria-label={slug === 'google-search-console' ? service.name : undefined}><ServiceLogo slug={slug} />{slug !== 'google-search-console' && service.name}</span>; })}<a href="#integrations">Все интеграции ↗</a></div></div></section>
    <section className="mk-section mk-container" id="scenarios"><div className="section-heading"><div><span className="eyebrow">01 / РАБОЧИЕ СЦЕНАРИИ</span><h2>Меньше выгрузок.<br />Больше работы по существу.</h2></div><p>Начните с привычной задачи. Ассистент запросит данные через ohmy-seo, сравнит их и подготовит результат для вашей проверки.</p></div><div className="scenario-grid">
      {[['01', 'Разобраться в рекламе', 'Какие кампании стали дороже? Где расход не приводит к конверсиям? Сравните показатели, поисковые запросы и настройки.', 'yandex-direct', 'Директ и Google Ads'], ['02', 'Найти точки роста SEO', 'Какие страницы потеряли клики? Где много показов и мало переходов? Получите список страниц и запросов для проверки.', 'google-search-console', 'Search Console и Вебмастер'], ['03', 'Собрать отчёт по маркетингу', 'Что изменилось в каналах и на посадочных страницах? Уточняйте период и показатели следующим сообщением.', 'google-analytics', 'Метрика, GA4 и Roistat'], ['04', 'Проверить семантику и теги', 'Сравните фразы по данным Mutagen, изучите выдачу через XMLStock или разберите конфигурацию контейнера GTM.', 'xmlstock', 'Mutagen, XMLStock и GTM']].map(([n, title, description, slug, names]) => <article className="scenario-card" key={n}><span className="card-number">{n}</span><h3>{title}</h3><p>{description}</p><a href={`/integrations/${slug}`}>{names} <span aria-hidden="true">↗</span></a></article>)}
    </div></section>
    <section className="mechanism"><div className="mk-container mechanism-grid"><div><span className="eyebrow">ПОНЯТНО О MCP</span><h2>AI получает контекст.<br />Вы принимаете решение.</h2><p>MCP — протокол, который соединяет AI-клиент с внешними инструментами. ohmy-seo даёт доступ к разрешённым данным. Выводы и текст отчёта готовит выбранная модель.</p><a className="text-link" href="/claude-mcp">Как подключить Claude к MCP ↗</a></div><ol className="flow-list"><li><span>1</span><div><strong>Вы задаёте вопрос</strong><p>Указываете проект, период и нужный результат.</p></div></li><li><span>2</span><div><strong>ohmy-seo обращается к сервисам</strong><p>Инструменты получают данные в рамках ваших прав.</p></div></li><li><span>3</span><div><strong>AI готовит ответ с опорой на данные</strong><p>Вы проверяете цифры, параметры и гипотезы.</p></div></li></ol></div></section>
    <section className="mk-section mk-container" id="integrations"><div className="section-heading"><div><span className="eyebrow">02 / ВЕСЬ ИНСТРУМЕНТАРИЙ</span><h2>От поискового запроса<br />до отчёта по результатам.</h2></div><p>Десять сервисов для разных этапов работы. У каждой интеграции — свои возможности и условия доступа.</p></div><div className="integration-grid">{integrations.map(i => <article className="integration-card" key={i.slug}><div className="integration-top"><span className="service-logo-slot"><ServiceLogo slug={i.slug} /></span><span>{i.category}</span></div><h3><a href={`/integrations/${i.slug}`}>{i.name} <span aria-hidden="true">↗</span></a></h3><p>{i.description.split(':').slice(1).join(':') || i.description}</p><div className="mode-label">{i.mode}</div></article>)}</div><p className="section-note">Облако: сервисы Яндекса, Search Console, GA4 и GTM — в рамках доступов аккаунта. Google Ads и Roistat устанавливаются отдельно. Mutagen и XMLStock требуют дополнительного доступа. <a href="/claude-mcp#local">Об установке пакетов →</a></p></section>
    <section className="mk-section prompt-section" id="prompts"><div className="mk-container"><div className="section-heading"><div><span className="eyebrow">03 / ПОПРОБУЙТЕ В РАБОТЕ</span><h2>Хороший запрос —<br />уже половина начала.</h2></div><div><p>Скопируйте пример, подставьте свой аккаунт и период. Все запросы ниже начинают с анализа.</p><a className="mk-button secondary" href="/prompts">Посмотреть все вопросы →</a></div></div><div className="prompt-grid">{[integrations[0], integrations[4], integrations[7]].map(i => <article className="prompt-card" key={i.slug}><span className="eyebrow">{i.name}</span><p>«{i.prompt}»</p><CopyText text={i.prompt} /></article>)}</div></div></section>
    <section className="mk-section mk-container" id="connect"><div className="section-heading"><div><span className="eyebrow">04 / ПОДКЛЮЧЕНИЕ</span><h2>От аккаунта<br />до первого вопроса.</h2></div><p>Начните с облачного подключения. Для дополнительных сервисов используйте локальные MCP-пакеты.</p></div><ol className="setup-grid"><li><span>01</span><h3>Подключите сервис</h3><p>Войдите через Яндекс. Затем отдельно подключите рабочие аккаунты Яндекса или Google внутри кабинета.</p></li><li><span>02</span><h3>Создайте API-ключ</h3><p>Выпустите персональный ключ для доступа к вашим подключениям.</p></li><li><span>03</span><h3>Добавьте MCP в AI-клиент</h3><p>Используйте адрес сервера и ключ. Начните с инструкции для Claude Code.</p></li><li><span>04</span><h3>Задайте первый вопрос</h3><p>Попросите показать доступные аккаунты и выберите источник для отчёта.</p></li></ol><a className="mk-button" href="/claude-mcp">Инструкция подключения Claude MCP ↗</a></section>
    <section className="control-section"><div className="mk-container control-grid"><div><span className="eyebrow">ДОСТУП ПОД КОНТРОЛЕМ</span><h2>Сначала данные.<br />Затем проверка.<br />Потом действие.</h2></div><div><article><h3>Чтение в облаке</h3><p>Запись по умолчанию выключена. Анализ отчётов не запускает рекламу и не меняет бюджеты.</p></article><article><h3>Управляемые изменения в пакетах</h3><p>Инструменты Директа, Google Ads и GTM умеют изменять данные. Для этого нужны соответствующие права, настройки и подтверждения.</p></article><article><h3>Прозрачные границы</h3><p>Доступ зависит от API и аккаунта. AI может ошибаться в выводах. Проверяйте источник, даты, метрики и план действий.</p></article><a href="/privacy">Как обрабатываются данные ↗</a></div></div></section>
    <section className="mk-section mk-container" id="access"><div className="section-heading"><div><span className="eyebrow">05 / ВАРИАНТЫ РАБОТЫ</span><h2>Выберите, как подключаться.</h2></div><p>ohmy-seo бесплатен для маркетологов — и в облаке, и при локальной установке. AI-клиенты и сторонние сервисы могут оплачиваться отдельно по их тарифам.</p></div><div className="access-grid"><article><span className="eyebrow">ОБЛАКО · БЕСПЛАТНО</span><h3>Готовый MCP-адрес</h3><p>Кабинет, подключения и персональный ключ. Сервисы доступны в пределах прав аккаунта и возможностей облачного режима.</p><a className="mk-button" href="/connect">Открыть кабинет ↗</a></article><article><span className="eyebrow">ЛОКАЛЬНЫЕ ПАКЕТЫ · БЕСПЛАТНО · MIT</span><h3>Инструменты на вашей машине</h3><p>Установите нужные пакеты из исходного кода. Настройте доступы сервисов и подключите процессы к своему AI-клиенту.</p><a className="mk-button secondary" href="/claude-mcp#local">Посмотреть настройку ↗</a></article></div></section>
    <section className="mk-section faq-section mk-container" id="faq"><div><span className="eyebrow">06 / ВОПРОСЫ И ОТВЕТЫ</span><h2>Что важно знать<br />до подключения.</h2></div><div className="faq-list">{faqs.map(([q,a]) => <details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
    <FinalCta />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'ohmy-seo', applicationCategory: 'BusinessApplication', operatingSystem: 'Web, macOS, Linux, Windows', url: 'https://ohmy-seo.ru', description: 'Бесплатный MCP-инструмент специально для маркетологов: реклама, SEO и аналитика', isAccessibleForFree: true, offers: { '@type': 'Offer', price: '0', priceCurrency: 'RUB' }, featureList: integrations.map(i=>i.name) }).replace(/</g, '\\u003c') }} />
  </main></MarketingShell>;
}
