import type { Metadata } from 'next';
import { ServiceLogo } from '@/components/marketing/ServiceLogo';
import { MarketingShell, FinalCta } from '@/components/marketing/Shell';
import { ScenarioDemo, CopyText } from '@/components/marketing/Interactive';
import { integrations, faqs } from '@/lib/marketing/catalog';

export const metadata: Metadata = {
  title: 'ohmy-seo — бесплатный MCP для маркетологов: Claude, Директ и Google Ads',
  description: 'Бесплатный инструмент для маркетологов: подключите Яндекс Директ, Google Ads, SEO и аналитику к Claude через MCP. Сценарии работы и инструкции.',
  alternates: { canonical: '/' },
  openGraph: { images: [{ url: "https://ohmy-seo.ru/og-image.png", width: 1200, height: 630, alt: "ohmy-seo — ваш маркетинг в диалоге с AI" }], type: "website", locale: "ru_RU", siteName: "ohmy-seo", title: 'Бесплатный MCP-инструмент для маркетологов', description: 'ohmy-seo создан специально для маркетологов: реклама, SEO и аналитика в диалоге с AI. Бесплатный доступ к инструменту.', url: '/' },
};

export default function Home() {
  return <MarketingShell><main id="main-content">
    <section className="mk-hero mk-container"><div className="hero-copy"><span className="eyebrow"><span className="live-dot" /> БЕСПЛАТНЫЙ MCP ДЛЯ МАРКЕТОЛОГОВ</span><h1>Реклама, SEO<br />и аналитика —<br /><em>из вашего AI-чата.</em></h1><p className="hero-lead">Подключите Директ, Метрику, Вебмастер и сервисы Google к Claude через MCP. Получайте отчёты, проверяйте гипотезы и меняйте настройки по своему запросу.</p><div className="mk-actions"><a className="mk-button" href="/connect">Начать бесплатно <span aria-hidden="true">↗</span></a><a className="mk-button secondary" href="#demo">Посмотреть пример ↓</a></div><p className="hero-note"><a className="text-link" href="https://github.com/VKirill/ohmy-seo" target="_blank" rel="noopener noreferrer">Открытый код на GitHub ↗</a><br />Бесплатно · MIT · Облако и локальные пакеты</p></div><div id="demo"><ScenarioDemo /></div></section>
    <section className="source-strip" aria-label="Поддерживаемые сервисы"><div className="mk-container"><span>РАБОТАЙТЕ С ДАННЫМИ</span><div>{['yandex-direct', 'google-ads', 'yandex-metrica', 'google-search-console', 'google-analytics', 'roistat'].map(slug => { const service = integrations.find(i => i.slug === slug)!; return <span className="strip-service" key={slug} aria-label={slug === 'google-search-console' ? service.name : undefined}><ServiceLogo slug={slug} />{slug !== 'google-search-console' && service.name}</span>; })}<a href="#integrations">Все интеграции ↗</a></div></div></section>
    <section className="mk-section mk-container" id="scenarios"><div className="section-heading"><div><span className="eyebrow">РАБОЧИЕ СЦЕНАРИИ</span><h2>Что поручить ассистенту</h2></div><p>Укажите аккаунт, период и задачу. Ассистент получит данные из подключённых сервисов и подготовит ответ или план изменений.</p></div><div className="scenario-grid">
      {[['01', 'Разобраться в рекламе', 'Какие кампании стали дороже? Где расход не приводит к конверсиям? Сравните показатели, поисковые запросы и настройки.', 'yandex-direct', 'Директ и Google Ads'], ['02', 'Найти точки роста SEO', 'Какие страницы потеряли клики? Где много показов и мало переходов? Получите список страниц и запросов для проверки.', 'google-search-console', 'Search Console и Вебмастер'], ['03', 'Собрать отчёт по маркетингу', 'Что изменилось в каналах и на посадочных страницах? Уточняйте период и показатели следующим сообщением.', 'google-analytics', 'Метрика, GA4 и Roistat'], ['04', 'Проверить семантику и теги', 'Сравните фразы по данным Mutagen, изучите выдачу через XMLStock или разберите конфигурацию контейнера GTM.', 'xmlstock', 'Mutagen, XMLStock и GTM']].map(([n, title, description, slug, names]) => <article className="scenario-card" key={n}><span className="card-number">{n}</span><h3>{title}</h3><p>{description}</p><a href={`/integrations/${slug}`}>{names} <span aria-hidden="true">↗</span></a></article>)}
    </div></section>
    <section className="mk-section mk-container" id="integrations"><div className="section-heading"><div><span className="eyebrow">ИНТЕГРАЦИИ</span><h2>Поддерживаемые сервисы</h2></div><p>Выберите сервис: здесь указаны задачи и способ подключения, а на его странице — возможности, права и примеры запросов.</p></div><div className="integration-list">{integrations.map(i => <article className="integration-row" key={i.slug}><div className="integration-service"><span className="service-logo-slot"><ServiceLogo slug={i.slug} /></span><h3><a href={`/integrations/${i.slug}`}>{i.name} <span aria-hidden="true">↗</span></a></h3></div><p>{i.description.split(':').slice(1).join(':') || i.description}</p><span className="integration-mode">{i.mode}</span></article>)}</div><p className="section-note">Облако: сервисы Яндекса, Search Console, GA4 и GTM — в рамках доступов аккаунта. Google Ads и Roistat устанавливаются отдельно. Mutagen и XMLStock требуют дополнительного доступа. <a href="/claude-mcp#local">Об установке пакетов →</a></p></section>
    <section className="mk-section prompt-section" id="prompts"><div className="mk-container"><div className="section-heading"><div><span className="eyebrow">ПРИМЕРЫ ЗАПРОСОВ</span><h2>Готовые задачи для MCP</h2></div><div><p>Скопируйте пример, подставьте свой аккаунт и период. Все запросы ниже начинают с анализа.</p><a className="mk-button secondary" href="/prompts">Посмотреть все вопросы →</a></div></div><div className="prompt-grid">{[integrations[0], integrations[4], integrations[7]].map(i => <article className="prompt-card" key={i.slug}><span className="eyebrow">{i.name}</span><p>«{i.prompt}»</p><CopyText text={i.prompt} /></article>)}</div></div></section>
    <section className="mk-section mk-container" id="connect"><div className="section-heading"><div><span className="eyebrow">НАСТРОЙКА</span><h2>Как подключить MCP</h2></div><p>Начните с облачного подключения. Для дополнительных сервисов используйте локальные MCP-пакеты.</p></div><ol className="setup-grid"><li><span>01</span><h3>Подключите сервис</h3><p>Войдите через Яндекс. Затем отдельно подключите рабочие аккаунты Яндекса или Google внутри кабинета.</p></li><li><span>02</span><h3>Создайте API-ключ</h3><p>Выпустите персональный ключ для доступа к вашим подключениям.</p></li><li><span>03</span><h3>Добавьте MCP в AI-клиент</h3><p>Используйте адрес сервера и ключ. Начните с инструкции для Claude Code.</p></li><li><span>04</span><h3>Задайте первый вопрос</h3><p>Попросите показать доступные аккаунты и выберите источник для отчёта.</p></li></ol><a className="mk-button" href="/claude-mcp">Инструкция подключения Claude MCP ↗</a></section>
    <section className="control-section"><div className="mk-container control-grid"><div><span className="eyebrow">ДОСТУП ПОД КОНТРОЛЕМ</span><h2>Как выполняются<br />изменения</h2></div><div><article><h3>Анализ и запись</h3><p>Облачный MCP умеет получать данные и выполнять доступные операции изменения в Директе, Метрике, Вебмастере, Search Console и GTM.</p></article><article><h3>Подтверждение операции</h3><p>Сервер требует явного подтверждения в вызове инструмента записи. Просите ассистента сначала показать аккаунт, объект и новые значения, затем подтверждайте нужное действие.</p></article><article><h3>Права подключённого аккаунта</h3><p>Доступ зависит от API и аккаунта. AI может ошибаться в выводах. Проверяйте источник, даты, метрики и план действий.</p></article><a href="/privacy">Как обрабатываются данные ↗</a></div></div></section>
    <section className="mk-section mk-container" id="access"><div className="section-heading"><div><span className="eyebrow">БЕСПЛАТНО ДЛЯ МАРКЕТОЛОГОВ</span><h2>Облако или локальная установка</h2></div><p>ohmy-seo бесплатен для маркетологов — и в облаке, и при локальной установке. AI-клиенты и сторонние сервисы могут оплачиваться отдельно по их тарифам.</p></div><div className="access-grid"><article><span className="eyebrow">ОБЛАКО · БЕСПЛАТНО</span><h3>Готовый MCP-адрес</h3><p>Кабинет, подключения и персональный ключ. Сервисы доступны в пределах прав аккаунта и возможностей облачного режима.</p><a className="mk-button" href="/connect">Открыть кабинет ↗</a></article><article><span className="eyebrow">ЛОКАЛЬНЫЕ ПАКЕТЫ · БЕСПЛАТНО · MIT</span><h3>Инструменты на вашей машине</h3><p>Установите нужные пакеты из исходного кода. Настройте доступы сервисов и подключите процессы к своему AI-клиенту.</p><a className="mk-button secondary" href="/claude-mcp#local">Посмотреть настройку ↗</a></article></div></section>
    <section className="mk-section faq-section mk-container" id="faq"><div><span className="eyebrow">FAQ</span><h2>Вопросы о сервисе</h2></div><div className="faq-list">{faqs.map(([q,a]) => <details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
    <FinalCta />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'ohmy-seo', applicationCategory: 'BusinessApplication', operatingSystem: 'Web, macOS, Linux, Windows', url: 'https://ohmy-seo.ru', description: 'Бесплатный MCP-инструмент специально для маркетологов: реклама, SEO и аналитика', isAccessibleForFree: true, offers: { '@type': 'Offer', price: '0', priceCurrency: 'RUB' }, featureList: integrations.map(i=>i.name) }).replace(/</g, '\\u003c') }} />
  </main></MarketingShell>;
}
